
services:
  postgres:
    image: postgres
    restart: unless-stopped
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_DB: 'metastore_db'
      POSTGRES_USER: 'hive'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5432:5432'
    volumes:
      - hive-db:/var/lib/postgresql
    networks:
      - hive

  metastore:
    image: apache/hive:3.1.3
    depends_on:
      - postgres
    restart: unless-stopped
    container_name: metastore
    hostname: metastore
    environment:
      DB_DRIVER: postgres
#      IS_RESUME: true
      VERBOSE: true
      SERVICE_NAME: 'metastore'
      SERVICE_OPTS: '-Xmx1G -Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver
                     -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://postgres:5432/metastore_db
                     -Djavax.jdo.option.ConnectionUserName=hive
                     -Djavax.jdo.option.ConnectionPassword=password'
    ports:
      - '9083:9083'
    volumes:
      - warehouse:/opt/hive/data/warehouse
      - ./hive-site.xml:/opt/hive/conf/hive-site.xml
      - type: bind
        source: ./postgresql.jar
        target: /opt/hive/lib/postgres.jar
    networks:
      - hive

  hiveserver2:
    image: apache/hive:3.1.3
    depends_on:
      - metastore
    restart: unless-stopped
    container_name: hiveserver2
    environment:
      HIVE_SERVER2_THRIFT_PORT: 10000
      SERVICE_OPTS: '-Xmx1G -Dhive.metastore.uris=thrift://metastore:9083'
      IS_RESUME: 'true'
      SERVICE_NAME: 'hiveserver2'
    ports:
      - '10000:10000'
      - '10002:10002'
    volumes:
      - warehouse:/opt/hive/data/warehouse
      - ./hive-site.xml:/opt/hive/conf/hive-site.xml
    networks:
      - hive
#  namenode:
#      image: apache/hadoop:3.3.5
#      hostname: namenode
#      container_name: namenode
#      command: ["hdfs", "namenode"]
#      ports:
#        - 9870:9870
#        - 9000:9000
#      env_file:
#        - ./config
#      environment:
#          ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
#      networks:
#        - hive
#  datanode:
#      image: apache/hadoop:3.3.5
#      command: ["hdfs", "datanode"]
#      env_file:
#        - ./config
#      networks:
#        - hive
#  resourcemanager:
#      image: apache/hadoop:3.3.5
#      hostname: resourcemanager
#      command: ["yarn", "resourcemanager"]
#      ports:
#         - 8088:8088
#      env_file:
#        - ./config
#      networks:
#        - hive
#  nodemanager:
#      image: apache/hadoop:3.3.5
#      command: ["yarn", "nodemanager"]
#      env_file:
#        - ./config
#      networks:
#        - hive
volumes:
  hive-db:
  warehouse:

networks:
  hive:
    name: hive