
services:
  namenode:
    image: apache/hadoop:3.3.5
    hostname: namenode
    ports:
      - 9870:9870
    env_file:
      - ./config
    environment:
      ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
    volumes:
      - ./hdfs-namenode-data:/tmp/hadoop-hadoop/dfs/name
    networks:
      - QLTT
      
    command: ["hdfs", "namenode"]

  datanode_1:
    image: apache/hadoop:3.3.5
    container_name: datanode-1
    command: [ "hdfs", "datanode" ]
    env_file:
      - ./config
    environment:
      - HDFS_DATA_DIR=/tmp/hadoop-root/dfs/data
    volumes:
      - ./hdfs-datanode-data:/tmp/hadoop-root/dfs/data
    networks:
      - QLTT

  resourcemanager:
    image: apache/hadoop:3.3.5
    container_name: resourcemanager
    hostname: resourcemanager
    command: [ "yarn", "resourcemanager" ]
    ports:
      - 8088:8088
    env_file:
      - ./config
    # volumes:
    #   - ./test.sh:/opt/test.sh
    networks:
      - QLTT

  nodemanager:
    image: apache/hadoop:3.3.5
    container_name: nodemanager
    command: [ "yarn", "nodemanager" ]
    env_file:
      - ./config
    networks:
      - QLTT

networks:
  QLTT:
    name: QLTT